version: 0.1
tasks:
  - name: python version
    image: python
    commands: |
      echo start task1
      python --version
      echo end task1
  - name: node version
    image: python
    commands: |
      echo start task2
      node --version
      echo end task2
