version: 0.1
tasks:
  build:
    docker:
      image: python
    environment:
      FOO: bar
    secrets:
      FOO_SECRET: SECRET123
    steps:
      - echo start build
      - checkout
      - ls -la
      - echo $FOO
      - echo $FOO_SECRET
      - echo end build

  test:
    docker:
      image: node
    requires:
      - build
    steps:
      - echo start test
      - node --version
      - echo end test
