#fake push 6
steps:
  - name: "checkout"
    image: "truc"
    commands: |
      git clone https://github.com/rcornu/swarm-android.git
      ls -la

  - name: "echo"
    image: "truc"
    commands: |
      echo hello
      wskljlmekjsdq
