version: 0.1
tasks:
  build:
    docker:
      image: python
    environment:
      FOO: bar
    steps:
      - echo start build
      - checkout
      - ls -la
      - echo $FOO
      - echo end build

  test:
    docker:
      image: node
    requires:
      - build
    steps:
      - echo start test
      - node --version
      - echo end test

  deploy:
    docker:
      image: node
    requires:
      - test
    steps:
      - echo start deploy
      - node --version
      - echo end deploy
