version: 0.1
tasks:
  build:
    docker:
      image: python
    steps:
      - echo start task1
      - checkout
      - errrorrr
      - echo end task1

  deploy:
    docker:
      image: node
    steps:
      - echo start task2
      - node --version
      - echo end task2
