#fake push 16
steps:
  - name: "checkout"
    image: "truc"
    commands: |
      echo "=> checkout"
      git clone https://github.com/rcornu/swarm-android.git
      ls -la
      echo "=> end

#  - name: "echo"
#    image: "truc"
#    commands: |
#      echo helloooo
