# 14
steps:
  - name: checkout
    commands: |
      echo "=> checkout"
      git clone https://github.com/rcornu/swarm-android.git
      ls -la
      echo "=> end4"

  - name: echo
    runtime: docker
    commands: |
      echo helloooo
      docker ps
