version: 0.1
tasks:
  build:
    docker:
      image: python
    environment:
      FOO: bar
    steps:
      - echo start task1
      - checkout
      - ls -la
      - echo $FOO
      - echo end task1

  deploy:
    docker:
      image: node
    requires:
      - build
    steps:
      - echo start task2
      - node --version
      - echo end task2
